version: "3"

services:
  database:
    build: ./database
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "25432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/code:/var/opt/gis

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/code/src:/var/opt/gis/src

volumes:
  database-data:
